tasks:
  - name: Podman
    command: |
      . /etc/os-release
      echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
      curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
      sudo apt update && sudo apt install -y podman crun
      sudo sed -i '/graphroot/c\graphroot = "/workspace/containers/storage"' /etc/containers/storage.conf
      sudo sed -i -e '/default_sysctls/,+2 s/^/#/'  /usr/share/containers/containers.conf
      sudo sed -i '/keyring=true/c\keyring=false'  /usr/share/containers/containers.conf
      sudo podman run --rm -it alpine sh